name: "Vultron"
description: "(Kalsarikännit) Obsługa wielu dzieci z konta EduVulcan. Automatyczne pobieranie ocen, planu i zadań."
url: "https://github.com/htomasz/vultron"
version: "1.0"
slug: "vultron"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
map:
  - config:rw
options:
  city_slug: ""
  username: ""
  password: ""
  period_id: "40732"
schema:
  city_slug: str
  username: str
  password: password
  period_id: str
